### ISSUE TITLE
SSUI - Show Contributor Submission Statuses

### ISSUE THREAD

**Issue by jakeclark** [Datastillery/smartcitiesdata#1017]
As a contributor, I need to be able to see my submitted dataset list, as well as be able to submit a new dataset for review, so that may contribute datatsets. 

- [ ] Status column uses the matrix referenced below to show the status based off of the Dataset Status and the Ingestion Status

Note - this card updates the language of the status section: Success, Error, Submitted, Rejected

![SSUI-User](https://user-images.githubusercontent.com/430082/96883980-ff68e080-144e-11eb-828c-931056d41b52.png)

**Comment by JarredOlson** [comment]
![Andi_Status_-_Google_Sheets.png](https://images.zenhubusercontent.com/5d0a9518df158845874ae67c/041f9e7e-7e39-49dd-8b6e-2be0f3c9ef08)
