### ISSUE TITLE
Unable to download FYBR Short North Parking Occupancy dataset

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#1051]
Look into issue submitted via Smart Columbus OS Contact Form: 

Hello!

I'm interested in the FYBR Short North Parking Occupancy dataset (https://discovery.smartcolumbusos.com/dataset/fybr/short_north_parking_occupancy). However, the JSON file never completely downloads from the site. The farthest I've gotten is 2.33 GB (sometimes it stops after 300 mb, sometimes it goes further), and I estimate the total should be around 28 GB or so based on the data structure. Are there alternative methods to get the data?

Thanks,

**Comment by bbrewer-forge** [comment]
https://github.com/benoitc/hackney/issues/638

**Comment by bbrewer-forge** [comment]
Downgrading hackney to deal with this.
