### ISSUE TITLE
Fix remaining datasets so that they can be migrated to extract steps

### ISSUE THREAD

**Issue by jessie-morris** [Datastillery/smartcitiesdata#1057]
AC:
- [x] ffe10222-cd58-4618-a11c-7870a8169625 - Updated dataset to use ingest steps.  Dataset is no longer being ingested
- [x] 7d22b8b4-2365-4afa-9b7c-e27b39c3e710 - Dataset is able to be edited via Andi
- [x] 88765083-c2e6-45c8-9123-4308767de5c4
- [x] 3228478d-0071-4cc3-91f7-a6c75d3ed945
- [x] 35fa9aef-04d0-4d56-b137-75a1047674de
- [x] fbe44c26-087d-4487-a35e-dcd241736bff
- [x] 30d3740d-d255-4d68-8282-fde0968ba41a

This card includes notes for datasets that Jessie ran into issues with while playing [Migrate Existing Datasets to Extract Steps #942](https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/942)

For dataset ffe10222-cd58-4618-a11c-7870a8169625 we get error:

   "technical": {
            "cadence": [
                "Cron schedule has a minimum interval of every 10 seconds"
            ]
        }

For dataset  7d22b8b4-2365-4afa-9b7c-e27b39c3e710 we get error (since cadence is continuous)[This also happens for the other continuous dataset]:

        "technical": {
            "cadence": [
                "Cron schedule has a minimum interval of every 10 seconds"
            ]
        }

error on dataset  88765083-c2e6-45c8-9123-4308767de5c4
{
  "errors": {
    "technical": {
      "cadence": [
        "Can't parse 0 as month."
      ]
    }
  }
}

Datasets 
3228478d-0071-4cc3-91f7-a6c75d3ed945
35fa9aef-04d0-4d56-b137-75a1047674de
fbe44c26-087d-4487-a35e-dcd241736bff
30d3740d-d255-4d68-8282-fde0968ba41a

have time zone  components which likely need to be looked at a bit closer.

**Comment by JulieMaterni** [comment]
Create additional cards if there are unresolvable issues.

**Comment by jessie-morris** [comment]
Editing my posts I see :-)
