### ISSUE TITLE
Andi Validation Updates

### ISSUE THREAD

**Issue by JarredOlson** [Datastillery/smartcitiesdata#1058]
AC:
- [x] Allow cadence of continuous
- [x] Allow Cron of every 2 seconds instead of every 10 seconds

**Comment by LtChae** [comment]
Linden requires a cron of every 2 seconds. Should that be the min instead?

**Comment by sukaant** [comment]
https://github.com/Datastillery/smartcitiesdata/pull/1133
https://github.com/SmartColumbusOS/andi-deploy/pull/187
