### ISSUE TITLE
SSUI: Upload Data sample to populate data dictionary

### ISSUE THREAD

**Issue by jakeclark** [Datastillery/smartcitiesdata#1096]
As a contributor, I want an easy way to populate the data dictionary, via uploading a sample, so that I don't have to manually add fields to the schema. 

AC:

- [ ] Reuse the Upload mechanism from the Curator UI
- [ ] When Contributor choose a file, schema will be uploaded in the background, and results populated automatically
- [ ] Instructions have changed to a message to review the data dictionary, as the schema will have been populated by uploading the data sample. 
- [ ] Include logging to note user who is uploading the sample data

Tech Notes:

- [ ] Data will not actually be uploaded - parsing of the schema will take place in-browser
![SSUI-Review-Data Dictionary](https://user-images.githubusercontent.com/430082/102234282-21b33380-3ebf-11eb-8dad-72d8e75a25b9.png)

**Comment by JulieMaterni** [comment]
Adding to the MVP epic. Originally this was planned as an enhancement, but since we finished the end-to-end MVP we are tracking to finish by end of January 2021.
