### ISSUE TITLE
SSUI: Upload Dataset Sample

### ISSUE THREAD

**Issue by jakeclark** [Datastillery/smartcitiesdata#1102]
As a contributor, I need a mechanism to upload my dataset, so that the Curator may review it. 

AC:
- [x] Create new S3 bucket just for storing data samples
- [x] Enable object deletion (via lifecycle policy) after 30 days
- [x] Enable access logging of object access (If guard duty is not doing this)
- [x] Bucket Versioning is disabled
- [x] Create an andi user in iam and add keys to vault
- [x] File is downloadable by Curator
- [x] Encryption Enabled
- [x] Limit file size to 250mb
- [x] Change header to say `Upload Dataset Sample`
- [x] Allow contributor to upload data sample
- [x] Only allow CSV, JSON, XML
- [x] Sample is required

![SSUI-Upload-Dataset](https://user-images.githubusercontent.com/430082/102237121-4c52bb80-3ec2-11eb-9a5d-c70993dcfdd5.png)

![SSUI-Upload-Dataset-Error](https://user-images.githubusercontent.com/430082/102237275-7e641d80-3ec2-11eb-863f-63650336fdf2.png)

![SSUI-Upload-Dataset-success](https://user-images.githubusercontent.com/430082/102237277-80c67780-3ec2-11eb-9e2a-72da464a3d5b.png)

**Comment by JulieMaterni** [comment]
Adding to the MVP epic. Originally this was planned as an enhancement, but since we finished the end-to-end MVP we are tracking to finish by end of January 2021.
