### ISSUE TITLE
CVE Reporting Red Light Running Use Case T-Shirt Size

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#1106]

**Comment by JulieMaterni** [comment]
Clearing out placeholder due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/326
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/327

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
