### ISSUE TITLE
SSUI: User Management- Add link to Navigation

### ISSUE THREAD

**Issue by jakeclark** [Datastillery/smartcitiesdata#1118]
As a curator or administrator, I want to be able to access the user administration interface, so that I may add, edit, or delete users. 

AC:

- [ ] Link in global navigation

![User-Management-nav.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/41140e87-77c9-40b1-a75a-be1e36e0ae1e)

**Comment by JulieMaterni** [comment]
@JarredOlson @jakeclark @ksmith-accenture @LtChae to get together to discuss user and organization workflows.
