### ISSUE TITLE
SSUI: User Management - Display List of Users

### ISSUE THREAD

**Issue by jakeclark** [Datastillery/smartcitiesdata#1119]
As a curator/administrator, I want to be able to view all users of the Dataset Ingestion Interface, including curators and contributors. 

AC:

- [ ] Reuse existing list and sorting patterns from the rest of the UI

![User-Management-List](https://user-images.githubusercontent.com/430082/102129428-52429100-3e1d-11eb-8f5a-bd879b266f30.png)

**Comment by JulieMaterni** [comment]
@JarredOlson @jakeclark @ksmith-accenture @LtChae to get together to discuss user and organization workflows.
