### ISSUE TITLE
SPIKE: Research Shared Streets and options for using with OS

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#1146]
We would like to research Shared Streets methodology to determine if it can be used to create data visualizations for PTA and MMTPA datasets. The goal of the visualizations would be to better understand where participants are coming from and going to in order to identify patterns and infrastructure needs. 

ACs:
- [ ] Can we use Shared Streets "viewer" with existing Pivot Data? https://discovery.smartcolumbusos.com/dataset/pivot/mmtpa
- [ ] Can we use Shared Streets Mobility Metrics (link in comments below) to process PII data and get into format similar to existing Pivot Data.  We will need to build a "plugin or adapter" to process this data possibly into MDS mobility data format.

Notes: 
- https://sharedstreets.io/pilots/
- https://mmapi.etch.app/metrics/
- Might want to reach out to Darlene and John from Etch to discuss further

**Comment by JulieMaterni** [comment]
Blocking - set up time with Darlene and John (Julie)

**Comment by JarredOlson** [comment]
https://www.openmobilityfoundation.org/about-mds/

Shared Streets mobility metrics should be able to read data and transform it using "Plugin/Adapter" would need to be written to to convert from PTA data into de-identified.

https://github.com/sharedstreets/mobility-metrics

**Comment by JarredOlson** [comment]
![Untitled drawing.png](https://images.zenhubusercontent.com/5d0a9518df158845874ae67c/2827407f-0526-40f3-bbf1-8aa0dc8bd848)

**Comment by JulieMaterni** [comment]
**Shared Streets and MDS for use in visualizing Prenatal Trip Assistance data**
I do not believe the Prenatal Trip Assistance data is convertable to the Shared Streets format. This is mainly due to either the lack of or low granularity of location data in the PTA dataset.

**Shared Streets**
The purpose of Shared Streets is, per their docs:
_Our global referencing system is used to move data between different street representations, whether data linked to OpenStreetMap, a city-managed GIS system, or a commercial basemap. We use linear referencing to identify specific street segments and subsegments (lines and points) and link them to a specific location along the street, regardless of your basemap._

Ultimately, the data standard is designed to anonymize and standardize mobility data by sectioning it into common street segments. Different types of data can all be broken down into those segments, allowing them to be directly compared on the same map.
The key piece of information needed to do this is the route the vehicle took. This is in the form of all the GPS locations logged by the vehicle (or other entity like a bike or scooter) from the start of its trip to the end. This allows the trip to be broken into shared streets' common street segments.

The Prenatal Trip Assistance data comes to us already anonymized, with at most the start and end zip codes. Even unredacted, the data dictionary indicates that it only contains the start and end address of the trip. If we had the unredacted data, a route finding api like Google Maps could be used to infer the trip, or to get the lat/long coordinates of the addresses as a geographic start and end, but this would not be the actual trip the vehicle took.

**Mobility Data Specification (MDS)**
This set of standards establishes a common language between mobility providers and regulatory agencies. It is less a data standard (though it does include some) and more an interface between the two. It lays out an application programming interface that can be implemented and used by both sides, allowing them to communicate in real time without the barriers of data requests and email chains.

**Shared Street Visualization**
There is no visualization library in the Shared Streets github repo. This is probably because the location data embedded in the Shared Streets format is itself in the geojson format, commonly accepted by most geo data visualization tools.
