### ISSUE TITLE
Curator UI Support Date and Timestamp Provider

### ISSUE THREAD

**Issue by JarredOlson** [Datastillery/smartcitiesdata#1148]
As a data curator I would like to be able to default a value to assist in data ingestion.

AC:
- [ ] Add support for Date Provider
- [ ] Add support for Timestamp Provider

Notes:
- Date Provider has an offset in days
- Timestamp Provider has an offset in seconds
- Both should default to 0
- checkbox to enable default value
- number input to specify offset value

![timestamp-unselected.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/209dab01-7bd7-49a8-95f9-8a9156b59e4a)
![timestamp-selected.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/d1fecb2b-af60-4ec3-92dc-4d4bb5968758)
![timestamp-modal.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/c4ead14f-cadb-4dc7-ade5-c58e10cf12c8)!
![date](https://user-images.githubusercontent.com/430082/105389634-0a661500-5be6-11eb-9088-851e78562ce2.png)

**Comment by JulieMaterni** [comment]
Work with Jake to get a comp.
