### ISSUE TITLE
Signal Priority Use Case T-Shirt Size

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#1158]

**Comment by JulieMaterni** [comment]
Original t-shirt size estimate = 5pts

Removing placeholder points due to the addition of the following cards (9pts):
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/334 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/335 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/336 (3pts)

**Comment by JulieMaterni** [comment]
Adding 2pt placeholder to account for unknowns.

**Comment by JulieMaterni** [comment]
Removing placeholder due to the addition of the following cards: 

- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1190 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1191 (2pts)

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
