### ISSUE TITLE
Provide Data Usage Report

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#1161]
As part of the OS Performance Measurement Plan, we will provide metrics on the usefulness of data on the operating system. As part of this, we will need metrics around dataset use. Run a report that includes the following:

- [x] Number of requests for datasets
- [x] Amount of time to access the data (Jake can pull from Google Analytics)
- [x] Number and frequency of dataset downloads from the OS
- [x] Number and frequency of dataset API calls from the OS
- [x] Number and frequency user submits queries for datasets
- [x] Number of visualizations created using datasets on the OS

**Comment by LtChae** [comment]
```elixir
DiscoveryApi.Schemas.Visualizations.list_visualizations |> Enum.count()

DiscoveryApi.Schemas.Visualizations.list_visualizations |> Enum.map(fn viz -> "\"#{viz.title}\",https://discovery.smartcolumbusos.com/visualization/#{viz.public_id}" end) |> Enum.each(&IO.puts/1)
```
