### ISSUE TITLE
Grant Reporting Support T-Shirt Size

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#1165]

**Comment by JulieMaterni** [comment]
Original t-shirt size = 25pts
Reducing to 18pts due to the addition of the following cards:

- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1175 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1166 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1150 (1pt)

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
