### ISSUE TITLE
Discovery API/UI: Display Presto Error Messages

### ISSUE THREAD

**Issue by LtChae** [Datastillery/smartcitiesdata#1175]
As a data consumer, I would like to see exact error messages for my queries so that I can quickly resolve issues and build my visualizations.

AC:
+ API returns presto error messages
+ Error messages should not reveal sensitive data such as whether tables exist
- [ ] Look into user roles. Can we use a user that does not have access to insert or delete?

TN:
- Error message for access denied and table does not exist should be identical.

Refinement notes:
+ This might be splittable into ui/api work

**Comment by JulieMaterni** [comment]
Need to create a whitelist of what things (not sensitive data) we can return to the user.
