### ISSUE TITLE
Run Historical Report #1 (1/11/21-2/28/21) for Signal Priority/Preemption Use Case

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#1190]
As part of the CVE Performance Measurement Plan, the team will need to run a final historical report that focuses on the effectiveness of signal priority/preemption operations. 

**Report timeframe: January 11, 2021 - February 28, 2021
Start running reports: March 1, 2021
Deliver reports to CVE team: March 8, 2021**

ACs: 
- [ ] Run travel time for emergency vehicles report
- [ ] Run idle time for freight vehicles report
- [ ] Run signal priority/preemption report
- [ ] Provide to CVE team for use in PfMP

**Comment by LtChae** [comment]
https://discovery.smartcolumbusos.com/dataset/smart_columbus_cve/cve_signal_preemption_requests
