### ISSUE TITLE
Andi: Update dataset's org name when org's name is changed

### ISSUE THREAD

**Issue by LtChae** [Datastillery/smartcitiesdata#1204]
**Describe the bug**
When an organization is renamed, that change is not propagated to datasets.

**To Reproduce**
1. Go to Organizations
2. Edit an organization, changing its name
3. Go back to datasets, see that datasets from that organization still have the old name in the table

**Expected behavior**
When an organization is renamed, that change is reflected in that org's datasets.

**Comment by bmitchinson** [comment]
From Refinement 6/9:
- Will require touching Andi, the Discovery API, and the event stream
- Right now a rename org event is being sent, but it only updates discovery API, and not the dataset itself
