### ISSUE TITLE
Andi: Feature Toggle Authentication for Evaluation Purposes

### ISSUE THREAD

**Issue by ksmith-accenture** [Datastillery/smartcitiesdata#1251]
# What?

Enable feature toggling of Andi's auth0 authentication.

Andi's Authentication:

- [ ] Should be toggled via an environment variable
- [ ] Should be on by default
- [ ] When disabled unauthenticated users should be administrators

# Why?

Without the administrative interface the data hub is pretty useless right out the gate.  Given evaluation deployments would not have ingress by default access would be limited to users who could port forward in the kubernetes cluster, which would be enough safeguards for an evaluation grade deployment.

**Comment by bmitchinson** [comment]
From Refinement 6/9
- Disabling user management would be required
