### ISSUE TITLE
Discovery API create index on startup

### ISSUE THREAD

**Issue by srashee1** [Datastillery/smartcitiesdata#1264]
#### User Story
As a system administrator

I want to be able to deploy discovery api on a new system and have it work without any manual steps

So that I can rapidly evaluate or restore an instance of the OS.

#### Acceptance Criteria: 
- [x] DiscoveryAPI should create a DatasetIndex on startup if it doesn't exist
- [x] Datasets are searchable via the UI from a fresh elastic search deployment.

#### Tech Notes: 
```  DiscoveryApi.Search.Elasticsearch.DatasetIndex.create() ```

#### Amigos: 
@LtChae 
@kMaiSmith

**Comment by bmitchinson** [comment]
To know that the API is "not working", you'll notice that searching datasets on the UI will respond with 400s API errors. The API will also be logging errors about elastic search.
