### ISSUE TITLE
Allow larger integer values in presto

### ISSUE THREAD

**Issue by abrock-accenture** [Datastillery/smartcitiesdata#173]
In reaper #134, we discovered that large integer values (larger than `2^31 - 1`) cannot be inserted into Presto.  Presto has a BIGINT type that can hold up to `2^63 - 1`.  We did some research and confirmed that with S3 as our backing datastore, there is no difference in the amount of space needed to store an integer value in an INTEGER column vs. a BIGINT column.

AC:
- All new tables should map integer types to Presto's BIGINT type, i.e. the `field_type` map should be updated to contain `"integer" => "bigint"`.

**Comment by rob-h-m** [comment]
Moved from carpenter 33 at Jarred's request
