### ISSUE TITLE
What alternatives exist to the ALB ingress controller?

### ISSUE THREAD

**Issue by jeffgrunewald** [Datastillery/smartcitiesdata#179]
How might we migrate a platform ingress solution from the current AWS specific one to a kube-native, cloud agnostic option. 

Considerations when formulating recommendations:
- Alternatives to explore (starting point only; not exhaustive): Nginx, Istio, Traefik
- How would SSL termination work?
- Where would we obtain SSL certificates (would Lets Encrypt work)?
- If a single lower-level cloud provider network load balancer fronts the k8s cluster, will the ingress solution handle host and path-based routing?
- Is there a loss of security functionality sending all web traffic to the cluster via lower-level load balancer option and can it be mitigated or improved on via other means (e.g. k8s network policies)?
- What is the optimal tradeoff of added functionality afforded by some solutions (API gateway, canary deployments, etc) vs. a simple routing ingress load balancer

ACs
- Recommendation of a preferred ingress controller
- Swag at cards (pre-grefinement) to implement

**Comment by jdenen** [comment]
@jeffgrunewald 
Can we find a way to describe this problem that doesn't read so Columbus-specific? I know what you're getting at -- and it is definitely a general platform concern -- but this reads like a Columbus only concern.

**Comment by jeffgrunewald** [comment]
Take a look at that @jdenen

**Comment by jdenen** [comment]
LGTM. Thanks @jeffgrunewald
