### ISSUE TITLE
Can we replace OWASP Zap with Arachni?

### ISSUE THREAD

**Issue by jeffgrunewald** [Datastillery/smartcitiesdata#180]
Can we reliably replace the OWASP Zap security scan with the Arachni tool?

Zap does not have the ability to delve into single-page applications and is trusting certain web content that may not be reliably trustworthy on the modern web. Arachni is a tool that purports to provide this capability.

Are there tradeoffs beyond the initial lift to transition to the solution? If so what are they?

ACs:
- Determine any loss of functionality by transitioning to Arachni
- Document the steps necessary to replace Zap with Arachni (cards, please)

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should move to SmartColumbusOS

Feel free to disagree @jeffgrunewald
