### ISSUE TITLE
Delete dataset in response to `dataset:delete` event

### ISSUE THREAD

**Issue by jakeprem** [Datastillery/smartcitiesdata#223]
ACs:

General
---
  * Dataset can be reingested as if it had never been in the system
  * Topics are cleaned up - either deleted or consumer groups are reset to HEAD
  * Any secrets and credentials for the dataset are cleaned up

Reaper
---
  * Reaper stops ingesting dataset
  * Reaper removes dataset from its Brook view state
  * Reaper does not reingest dataset when it restarts (unless a new event for the dataset is posted)

Valkyrie
---
  * Valkyrie deletes dataset from its view state

Forklift
---
  * Forklift deletes table and data
  * Forklift deletes `_compacted` table
  * Forklift deletes dataset from its view state

Discovery API
---
  * Discovery API deletes dataset from its view state

Andi
---
  * Andi deletes dataset from its view state

**Comment by mcsearchin** [comment]
This card should be broken up.  The separation is clear from for each of the apps, but the ACs under 'general' probably need to be fleshed out a bit more.

- Should each app be responsible for deleting/reset consumers for the topics it created?
- Which app should clean up secrets?  ANDI?
