### ISSUE TITLE
GeoJson parser for breaking up large files

### ISSUE THREAD

**Issue by jeffgrunewald** [Datastillery/smartcitiesdata#279]
We need a way for Reaper to parse GeoJson data frames that does not require the entire file to be ballooned into memory. This is crashing the app due to memory restrictions.

These files can be parsed into a simple stack where each data point of the geojson is treated as a "document" and sent along for ingestion.

AC:
This dataset should be ingestible without modification: https://discovery.smartcolumbusos.com/dataset/united_states_census_bureau/unified_school_districts_census

**Comment by rob-h-m** [comment]
@LtChae PING! See above....
