### ISSUE TITLE
Reaper can be configured to run an initial job with different parameters

### ISSUE THREAD

**Issue by LtChae** [Datastillery/smartcitiesdata#284]
As a data curator, when I ingest a new api with time-series data, I want to be able to ingest all data that has come before now as a batch and then ingest on a cadence going forward so that I have all the data the api can provide.

AC
+ Reaper can be configured to run an initial batch ingest with different parameters against a source url.

Grooming Notes:
+ This might need to be a feature of the Curator UI/Andi instead.

**Comment by ManApart** [comment]
This could take advantage of the 'multiple technicals' work we're considering.
