### ISSUE TITLE
Downstream applications kill their subscriber and move topic offset in response to dataset:purge event (was Valkyrie #87)

### ISSUE THREAD

**Issue by carriebrinkley** [Datastillery/smartcitiesdata#291]
@jmorris-pillar commented on [Thu Sep 19 2019](https://github.com/smartcitiesdata/smartcitiesdata/issues/150)

As a data curator, I want to be sure that when a dataset ingest is purged, the next triggered ingest will not contain old data.

AC:

- DiscoveryStreams kill their dataset subscriber and move their topic offset to :latest
- Upon starting reingestion, Discovery streams properly process the dataset and do not include records from the previous ingestion.
- The table is deleted when the action is executed
- Delete/archive compacted table

Things that we currently have to deal with:

  * Kafka Topics
  * Redis Keys
  * Brook View states
  * Reaper Supervisors
  * Presto Tables

**Comment by ManApart** [comment]
Right now I *believe* we have dataset:disable and dataset:delete. It sounds like purge is the same as delete?

**Comment by jmorris-pillar** [comment]
Yes, I believe it is now named dataset:delete.
