### ISSUE TITLE
Local testing environment for LDAP

### ISSUE THREAD

**Issue by LtChae** [Datastillery/smartcitiesdata#298]
**Value**
As an operating system developer, I would like to have accurate tests for changes made to discovery api authorization so that I can be confident the changes won't cause issues in production.

**AC**
- Provide production-like environment in integration environment.
   - Integration LDAP environment is structured like prod
   - LDAP configuration (aside from host) is identical for prod and integration

**Tech Notes**
This may require finding a different LDAP docker image

**Grooming Notes**
Is this worth doing with the upcoming changes to Auth?

**Comment by jdenen** [comment]
Our fork of `charts` includes baking these types of things into LDAP. I don't believe you'll need to choose a different LDAP image. See this for more:

https://github.com/JShefferPillar/charts/blob/3710bd53c5d6f91f70d1d6141ed243b20eba0414/platform/values.yaml#L12
