### ISSUE TITLE
Consistent Downcasing of Schema Field Names

### ISSUE THREAD

**Issue by mcsearchin** [Datastillery/smartcitiesdata#424]
Our database (presto) downcases all column names regardless of how they are defined in the dataset schema definition.  Because Presto does not support case-sensitivity, our system can't either.

ACs:
- System is case insensitive
- When the system gets data with keys that don't match the case of it's dataset definition, the system converts the data keys' case to match that of it's definition

TN:
- Probably just want to downcase all keys / dataset definitions in Andi, Reaper, and any other entry point/ service that consumes from the outside world
- Consider this with the push gateway as well

# Consider
Do Input and Output schema solve the issues here?

# Apps
- Andi
- Valkyrie
- Reaper
- Push Gateway
- discovery_api
- Flair?

Amigos:
@mcsearchin , @JarredOlson

**Comment by LtChae** [comment]
This card is hung up on a problem where we need the given casing in order to reference fields in json.

Currently, we reference json fields by name in order to extract their values:
```json
{
  "dataKeyOne": "some value"
}
```

would require a schema like

```json
{
  "name": "dataKeyOne",
  "type": "string",
  "description": "etc",
  ...
}
```

Because of this, we cannot at the moment enforce lowercase keys in Andi.

**Comment by LtChae** [comment]
Possible solutions:

+ Downcase all field names in incoming data
  + Could slow Reaper further (it is already the bottleneck in the pipeline)
  + Minor risk of duplicate field names ("dataKeyOne" and "datakeyOne" would both turn into the same field, but that is an unlikely scenario)
  + Relatively easy to do. We already crawl the incoming data in a few places.
+ JSON Selectors to map mixed case fields to our own named downcased fields
  + Requires a new schema field 
  + Unknown performance hit to Reaper 
  + Already implemented for XML
  + Has potential uses beyond this. (Flattening incoming data, excluding unused fields, etc.)
