### ISSUE TITLE
Valkyrie and other apps hang on direct acknowledger call

### ISSUE THREAD

**Issue by bbrewer-forge** [Datastillery/smartcitiesdata#601]
**Describe the bug**
Periodically valkyrie will stop reading from kafka for a dataset and never restart until valkyrie is restarted completely. It looks like it gets hung up while sending an acknowledgement to kafka.

**To Reproduce**
1. Wait a few weeks and valkyrie will do this

**Expected behavior**
It doesn't do this.

**Tech notes**
We are several versions behind on Elsa, which valkyrie uses to talk to kafka. There have been several brod and Elsa updates related to the acknowledger so it would be good to just roll that in and watch valkyrie with it for awhile

Potential Fixes
- [ ] Restart the process tree and/or the entire app when this situation occurs
- [ ] Upgrade Elsa

**Comment by bbrewer-papa-x** [comment]
An elsa upgrade "should" fix this
