### ISSUE TITLE
Select parent when subschema is empty

### ISSUE THREAD

**Issue by cameronmarsh** [Datastillery/smartcitiesdata#673]
When deleting a field from the dataset schema in Andi, there is logic in place to find the next selected field. When the last child of a parent's subschema is deleted, the parent should be the new selected field. However, this currently causes an error with liveview keeping track of its components. 

AC:
- [ ] When the last field in a parent's subschema is deleted, the parent should be able to be subsequently deleted without clicking on parent in the data dictionary tree

To reproduce this bug:

1. Have the parent field be selected when the subschema is empty by replacing the `:no_dictionary` return value in the `edit_live_view.ex` on line 383 with the following:
```elixir
technical_id =
  socket.assigns.changeset
  |> Changeset.fetch_change!(:technical)
  |> Changeset.fetch_change!(:id)

if deleted_field_parent_id == technical_id do
  :no_dictionary
else
  deleted_field_parent_id
end
```
2. In the browser, continue to delete all fields of a parent's subschema until the parent itself is selected
3. When you click the trash can icon to delete this field, the error will show in the development console

**Comment by cameronmarsh** [comment]
Image of the console error: 
![image.png](https://images.zenhubusercontent.com/5d0a8b44df158845874ae656/605cbbf9-2656-4877-9753-a831a65a0115)

**Comment by cameronmarsh** [comment]
A similar error submitted https://github.com/phoenixframework/phoenix_live_view/issues/759

**Comment by LtChae** [comment]
Blocked by this issue: https://github.com/phoenixframework/phoenix_live_view/issues/1121

**Comment by LtChae** [comment]
Code is in a branch called `parent-deletion-fix`
