### ISSUE TITLE
Creating Security Operations capabilities: Central logging and SIEM (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [Datastillery/smartcitiesdata#72]
Creating Security Operations capabilities: Central logging and SIEM (XL)
 * AWS logs including platform and tech (Cloudwatch, et cetera)
 * Prometheus and Graphana for metrics (in place)
 * Fluentd and kabana (in place)
 * Collect all the darn things

T-Shirt estimate was made on 05/31/19.
 * S: < 1 pair / .5 sprint
 * M: 1 pair / 1 sprint
 * L: 2 pairs / 1 sprint
 * XL: way >

07-02-2019 Migrated from SMRT-1323

**Comment by warnerAWESOMEmoore** [comment]
ELK/EFK is current in place for the EKS servers and app containers. Can potentially expand on that instead of building new.

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
