### ISSUE TITLE
 Encrypt everything (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [Datastillery/smartcitiesdata#73]
Encrypt everything, not just PII (at rest and in transit) (XL)

T-Shirt estimate was made on 05/31/19.
 * S: < 1 pair / .5 sprint
 * M: 1 pair / 1 sprint
 * L: 2 pairs / 1 sprint
 * XL: way >

07-02-2019 Migrated from SMRT-1324

**Comment by jdenen** [comment]
@rob-h-m
This is specific to Columbus and should move to SmartColumbusOS

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
