### ISSUE TITLE
Multi Factor Authentication for more than just PII / ops (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [Datastillery/smartcitiesdata#74]
Multi Factor Authentication for more than just PII / ops (L)

T-Shirt estimate was made on 05/31/19.
 * S: < 1 pair / .5 sprint
 * M: 1 pair / 1 sprint
 * L: 2 pairs / 1 sprint
 * XL: way >

07-02-2019 Migrated from SMRT-1325

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
