### ISSUE TITLE
Runtime Configurable Data (t-shirt)

### ISSUE THREAD

**Issue by carriebrinkley** [Datastillery/smartcitiesdata#800]

**Comment by JulieMaterni** [comment]
Reducing from 13 points to 8 points due to the addition of the following card: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/939 (5pts)

**Comment by JulieMaterni** [comment]
Reducing to 0 points. Any additional work will be considered an enhancement.

**Comment by dmiree** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
