### ISSUE TITLE
Parking Predictive Model 2.0 T-Shirt Size

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#861]

**Comment by JulieMaterni** [comment]
Original t-shirt size: 50 points

Reducing to 41 points due to adding the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/871 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/872 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/873 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/874 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/875 (3pts)

**Comment by JulieMaterni** [comment]
Removing placeholder per Dan's message 8/20:

I believe the cards we reviewed today will get me through the next two weeks, and they capture the work required to get to a working end-to-end prediction service. When they're done the predictive service will be capable of responding to parking meter and zone updates made by the city, but its predictions will be roughly the same as they are today.

There is plenty more to do in September once this work is completed, but all of it falls into the "nice-to-have" category.

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
