### ISSUE TITLE
SPIKE: Audit internal systems and determine if any need Multi-Factor Authentication

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#899]
As a Smart Columbus developer, I want to have multi-factor authentication on my internal systems so that I can protect their sensitive information and reduce the risk should a system's password be compromised.

ACs: 
- [ ] Audit internal systems and document any that do not have multi-factor authentication
- [ ] Create cards to add MFA to those systems that do not already have it

Notes: 
- The priority is environments and users with administrative privileges. 

Thoughts:
- AWS
- auth0 admin accounts
- VPN accounts
- jenkins
- joomla
- lime

**Comment by warnerAWESOMEmoore** [comment]
The priority is environments and users with administrative privileges. Thanks!

**Comment by JulieMaterni** [comment]
Paused security enhancements until February 2021. Will plan to play this spike in January so we understand the size of the feature.
