### ISSUE TITLE
SPIKE: Review systems/services and determine what needs encryption

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#900]
As a Smart Columbus developer, I want my systems and services to be encrypted so that my systems, services and data will be protected and secure.

ACs:
- [ ] Audit existing services and systems and identify those that are not currently encrypted
- [ ] Create cards to encrypt those services and systems that are not

Notes:
- This applies to information in transit and at rest both on internal and external networks.

- RDS Encrypt at Rest
- Elasticsearch (might be excluded since we don't put sensitive date in there)
- EBS volumes
- HTTPS to be used by internal services

**Comment by warnerAWESOMEmoore** [comment]
This applies to information in transit and at rest both on internal and external networks. Thanks!

**Comment by JulieMaterni** [comment]
Paused security enhancements until February 2021. Will plan to play this spike in January so we understand the size of the feature.
