### ISSUE TITLE
Synchronization of ANDI's view of a dataset and the common system view

### ISSUE THREAD

**Issue by bbrewer-forge** [Datastillery/smartcitiesdata#908]
#### User Story
As a developer

I want to see Andi.InputSchemas.Dataset and SmartCity.Dataset synchronized when sending and receiving "dataset:update" events.

So that data is not lost when editing datasets that have fields that are not exposed in the UI, so my life is better.

#### Acceptance Criteria: 
When a dataset is sent to ANDI via a "dataset:update" with fields that are not in Andi's Dataset schema
and that dataset is edited in the ANDI UI, and published
- [ ]  no data (technical, business, etc.) is lost on the SmartCity.Dataset when it arrives on the event-stream elsewhere

#### Tech Notes: 
- In the past we stored the original SmartCity.Dataset during the UI edit process and the merged the UI version and stored version back together before sending a dataset:update
- Get out of view state

#### Amigos: 
@bbrewer-forge @cameronmarsh

**Comment by JulieMaterni** [comment]
Have conversation with Cam before prioritizing or playing this card.
