### ISSUE TITLE
Properties T-Shirt Size 

### ISSUE THREAD

**Issue by JulieMaterni** [Datastillery/smartcitiesdata#934]

**Comment by JulieMaterni** [comment]
Original t-shirt size = 8pts
Reducing to 6pts due to the addition of the following card: 
- https://app.zenhub.com/workspace/o/datastillery/smartcitiesdata/issues/1014 (2pts)

**Comment by JulieMaterni** [comment]
Removing t-shirt size due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1035 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1040 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1041 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1042 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1043 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1044 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1045 (1pt)

**Comment by jessicapfoster** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
