### ISSUE TITLE
Andi allows publish without a cadence

### ISSUE THREAD

**Issue by cameronmarsh** [Datastillery/smartcitiesdata#960]
In andi, a user can post a dataset without selecting an option in the finalize section. However, this causes problems further down in the ingestion process

To reproduce: fill out a new dataset, adding all fields but leaving the radio buttons on the finalize section blank. Publish the dataset and see that it has "published successfully"

AC:
- [ ] Show error message in the finalize section that prevents a user from publishing a dataset without any cadence set

**Comment by JulieMaterni** [comment]
@cameronmarsh to see if this is reproducible.

**Comment by cameronmarsh** [comment]
It's reproducible
