### ISSUE TITLE
SSUI: Access Contributor Andi from Discovery

### ISSUE THREAD

**Issue by jakeclark** [Datastillery/smartcitiesdata#977]
As a contributor, I need a way to access Andi from Discovery, so that I may submit a dataset for review. 

AC:

- [ ] A link to CA (Contributor Andi) will live in the "My Account" dropdown
- [ ] Link CTA is "My Datasets"

http://sharedata.smartcolumbusos.com/

![image](https://user-images.githubusercontent.com/430082/95355936-1bd41d00-0894-11eb-8a56-daa88745dfa7.png)

**Comment by JulieMaterni** [comment]
This will likely be the last card played for Self-Service MVP as it will make the feature publicly accessible.
