### ISSUE TITLE
SSUI: Dataset Link Section

### ISSUE THREAD

**Issue by jakeclark** [Datastillery/smartcitiesdata#981]
As a contributor, I need a field to enter the link for my dataset, so that the Curator can easily click on it to review my dataset in a secure environment. 

AC:

- [x] "Configure Upload" header becomes "Dataset Link"
- [ ] The only field is for the URL to the dataset on the contributor's host
- [ ] Label for field is more explanatory about what should be entered 

![SSUI-Dataset-Link](https://user-images.githubusercontent.com/430082/96620200-23081b80-12d5-11eb-875a-076277cb3df0.png)

**Comment by JulieMaterni** [comment]
As part of this card @kcarra will update the Help link in the data dictionary section to point to the same Help link as the metadata section.
